export const START_FETCH_PRODUCTS = "START_FETCH_PRODUCTS";
export const SAVE_SEARCH_WORD = "SAVE_SEARCH_WORD";
export const LOADED_CATEGORIES_PRODUCTS = "LOADED_CATEGORIES_PRODUCTS";
export const ERROR_LOADED_PRODUCTS = "ERROR_LOADED_PRODUCTS";
export const SET_QUANTITY_PRODUCTS_ON_CHANGE =
  "SET_QUANTITY_PRODUCTS_ON_CHANGE";
export const SET_QUANTITY_PRODUCTS_ON_CHANGE_LOADING =
  "SET_QUANTITY_PRODUCTS_ON_CHANGE_LOADING";
